<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
  public function run(): void
  {
    DB::table('surah')->insert([
      ['surah_name' => '1. Al-Fatihah', 'ayat' => 7],
      ['surah_name' => '2. Al-Baqarah', 'ayat' => 286],
      ['surah_name' => '3. Ali Imran', 'ayat' => 200],
      ['surah_name' => '4. An-Nisa', 'ayat' => 176],
      ['surah_name' => '5. Al-Maidah', 'ayat' => 120],
      ['surah_name' => '6. Al-An’am', 'ayat' => 165],
      ['surah_name' => '7. Al-A’raf', 'ayat' => 206],
      ['surah_name' => '8. Al-Anfal', 'ayat' => 75],
      ['surah_name' => '9. At-Taubah', 'ayat' => 129],
      ['surah_name' => '10. Yunus', 'ayat' => 109],
      ['surah_name' => '11. Hud', 'ayat' => 123],
      ['surah_name' => '12. Yusuf', 'ayat' => 111],
      ['surah_name' => '13. Ar-Ra’d', 'ayat' => 43],
      ['surah_name' => '14. Ibrahim', 'ayat' => 52],
      ['surah_name' => '15. Al-Hijr', 'ayat' => 99],
      ['surah_name' => '16. An-Nahl', 'ayat' => 128],
      ['surah_name' => '17. Al-Isra', 'ayat' => 111],
      ['surah_name' => '18. Al-Kahf', 'ayat' => 110],
      ['surah_name' => '19. Maryam', 'ayat' => 98],
      ['surah_name' => '20. Ta-Ha', 'ayat' => 135],
      ['surah_name' => '21. Al-Anbiya', 'ayat' => 112],
      ['surah_name' => '22. Al-Hajj', 'ayat' => 78],
      ['surah_name' => '23. Al-Mu’minun', 'ayat' => 118],
      ['surah_name' => '24. An-Nur', 'ayat' => 64],
      ['surah_name' => '25. Al-Furqan', 'ayat' => 77],
      ['surah_name' => '26. Ash-Shu’ara', 'ayat' => 227],
      ['surah_name' => '27. An-Naml', 'ayat' => 93],
      ['surah_name' => '28. Al-Qasas', 'ayat' => 88],
      ['surah_name' => '29. Al-Ankabut', 'ayat' => 69],
      ['surah_name' => '30. Ar-Rum', 'ayat' => 60],
      ['surah_name' => '31. Luqman', 'ayat' => 34],
      ['surah_name' => '32. As-Sajda', 'ayat' => 30],
      ['surah_name' => '33. Al-Ahzab', 'ayat' => 73],
      ['surah_name' => '34. Saba', 'ayat' => 54],
      ['surah_name' => '35. Fatir', 'ayat' => 45],
      ['surah_name' => '36. Ya-Sin', 'ayat' => 83],
      ['surah_name' => '37. As-Saffat', 'ayat' => 182],
      ['surah_name' => '38. Sad', 'ayat' => 88],
      ['surah_name' => '39. Az-Zumar', 'ayat' => 75],
      ['surah_name' => '40. Ghafir', 'ayat' => 85],
      ['surah_name' => '41. Fussilat', 'ayat' => 54],
      ['surah_name' => '42. Ash-Shura', 'ayat' => 53],
      ['surah_name' => '43. Az-Zukhruf', 'ayat' => 89],
      ['surah_name' => '44. Ad-Dukhan', 'ayat' => 59],
      ['surah_name' => '45. Al-Jathiya', 'ayat' => 37],
      ['surah_name' => '46. Al-Ahqaf', 'ayat' => 35],
      ['surah_name' => '47. Muhammad', 'ayat' => 38],
      ['surah_name' => '48. Al-Fath', 'ayat' => 29],
      ['surah_name' => '49. Al-Hujurat', 'ayat' => 18],
      ['surah_name' => '50. Qaf', 'ayat' => 45],
      ['surah_name' => '51. Adh-Dhariyat', 'ayat' => 60],
      ['surah_name' => '52. At-Tur', 'ayat' => 49],
      ['surah_name' => '53. An-Najm', 'ayat' => 62],
      ['surah_name' => '54. Al-Qamar', 'ayat' => 55],
      ['surah_name' => '55. Ar-Rahman', 'ayat' => 78],
      ['surah_name' => '56. Al-Waqia', 'ayat' => 96],
      ['surah_name' => '57. Al-Hadid', 'ayat' => 29],
      ['surah_name' => '58. Al-Mujadila', 'ayat' => 22],
      ['surah_name' => '59. Al-Hashr', 'ayat' => 24],
      ['surah_name' => '60. Al-Mumtahana', 'ayat' => 13],
      ['surah_name' => '61. As-Saff', 'ayat' => 14],
      ['surah_name' => '62. Al-Jumua', 'ayat' => 11],
      ['surah_name' => '63. Al-Munafiqun', 'ayat' => 11],
      ['surah_name' => '64. At-Taghabun', 'ayat' => 18],
      ['surah_name' => '65. At-Talaq', 'ayat' => 12],
      ['surah_name' => '66. At-Tahrim', 'ayat' => 12],
      ['surah_name' => '67. Al-Mulk', 'ayat' => 30],
      ['surah_name' => '68. Al-Qalam', 'ayat' => 52],
      ['surah_name' => '69. Al-Haqqa', 'ayat' => 52],
      ['surah_name' => '70. Al-Maarij', 'ayat' => 44],
      ['surah_name' => '71. Nuh', 'ayat' => 28],
      ['surah_name' => '72. Al-Jinn', 'ayat' => 28],
      ['surah_name' => '73. Al-Muzzammil', 'ayat' => 20],
      ['surah_name' => '74. Al-Muddathir', 'ayat' => 56],
      ['surah_name' => '75. Al-Qiyama', 'ayat' => 40],
      ['surah_name' => '76. Al-Insan', 'ayat' => 31],
      ['surah_name' => '77. Al-Mursalat', 'ayat' => 50],
      ['surah_name' => '78. An-Naba', 'ayat' => 40],
      ['surah_name' => '79. An-Naziat', 'ayat' => 46],
      ['surah_name' => '80. Abasa', 'ayat' => 42],
      ['surah_name' => '81. At-Takwir', 'ayat' => 29],
      ['surah_name' => '82. Al-Infitar', 'ayat' => 19],
      ['surah_name' => '83. Al-Mutaffifin', 'ayat' => 36],
      ['surah_name' => '84. Al-Inshiqaq', 'ayat' => 25],
      ['surah_name' => '85. Al-Buruj', 'ayat' => 22],
      ['surah_name' => '86. At-Tariq', 'ayat' => 17],
      ['surah_name' => '87. Al-Ala', 'ayat' => 19],
      ['surah_name' => '88. Al-Ghashiya', 'ayat' => 26],
      ['surah_name' => '89. Al-Fajr', 'ayat' => 30],
      ['surah_name' => '90. Al-Balad', 'ayat' => 20],
      ['surah_name' => '91. Ash-Shams', 'ayat' => 15],
      ['surah_name' => '92. Al-Lail', 'ayat' => 21],
      ['surah_name' => '93. Ad-Duhaa', 'ayat' => 11],
      ['surah_name' => '94. Ash-Sharh', 'ayat' => 8],
      ['surah_name' => '95. At-Tin', 'ayat' => 8],
      ['surah_name' => '96. Al-Alaq', 'ayat' => 19],
      ['surah_name' => '97. Al-Qadr', 'ayat' => 5],
      ['surah_name' => '98. Al-Bayyina', 'ayat' => 8],
      ['surah_name' => '99. Az-Zalzala', 'ayat' => 8],
      ['surah_name' => '100. Al-Adiyat', 'ayat' => 11],
      ['surah_name' => '101. Al-Qaria', 'ayat' => 11],
      ['surah_name' => '102. At-Takathur', 'ayat' => 8],
      ['surah_name' => '103. Al-Asr', 'ayat' => 3],
      ['surah_name' => '104. Al-Humaza', 'ayat' => 9],
      ['surah_name' => '105. Al-Fil', 'ayat' => 5],
      ['surah_name' => '106. Quraysh', 'ayat' => 4],
      ['surah_name' => '107. Al-Maun', 'ayat' => 7],
      ['surah_name' => '108. Al-Kawthar', 'ayat' => 3],
      ['surah_name' => '109. Al-Kafirun', 'ayat' => 6],
      ['surah_name' => '110. An-Nasr', 'ayat' => 3],
      ['surah_name' => '111. Al-Masad', 'ayat' => 5],
      ['surah_name' => '112. Al-Ikhlas', 'ayat' => 4],
      ['surah_name' => '113. Al-Falaq', 'ayat' => 5],
      ['surah_name' => '114. An-Nas', 'ayat' => 6],
    ]);
  }
}
