<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('surah')->insert([
      ['surah_name' => 'Al-Fatihah', 'ayat' => 7],
      ['surah_name' => 'Al-Baqarah', 'ayat' => 286],
      ['surah_name' => 'Ali Imran', 'ayat' => 200],
      ['surah_name' => 'An-Nisa', 'ayat' => 176],
      ['surah_name' => 'Al-Maidah', 'ayat' => 120],
      ['surah_name' => 'Al-An’am', 'ayat' => 165],
      ['surah_name' => 'Al-A’raf', 'ayat' => 206],
      ['surah_name' => 'Al-Anfal', 'ayat' => 75],
      ['surah_name' => 'At-Taubah', 'ayat' => 129],
      ['surah_name' => 'Yunus', 'ayat' => 109],
      ['surah_name' => 'Hud', 'ayat' => 123],
      ['surah_name' => 'Yusuf', 'ayat' => 111],
      ['surah_name' => 'Ar-Ra’d', 'ayat' => 43],
      ['surah_name' => 'Ibrahim', 'ayat' => 52],
      ['surah_name' => 'Al-Hijr', 'ayat' => 99],
      ['surah_name' => 'An-Nahl', 'ayat' => 128],
      ['surah_name' => 'Al-Isra', 'ayat' => 111],
      ['surah_name' => 'Al-Kahf', 'ayat' => 110],
      ['surah_name' => 'Maryam', 'ayat' => 98],
      ['surah_name' => 'Ta-Ha', 'ayat' => 135],
      ['surah_name' => 'Al-Anbiya', 'ayat' => 112],
      ['surah_name' => 'Al-Hajj', 'ayat' => 78],
      ['surah_name' => 'Al-Mu’minun', 'ayat' => 118],
      ['surah_name' => 'An-Nur', 'ayat' => 64],
      ['surah_name' => 'Al-Furqan', 'ayat' => 77],
      ['surah_name' => 'Ash-Shu’ara', 'ayat' => 227],
      ['surah_name' => 'An-Naml', 'ayat' => 93],
      ['surah_name' => 'Al-Qasas', 'ayat' => 88],
      ['surah_name' => 'Al-Ankabut', 'ayat' => 69],
      ['surah_name' => 'Ar-Rum', 'ayat' => 60],
      ['surah_name' => 'Luqman', 'ayat' => 34],
      ['surah_name' => 'As-Sajda', 'ayat' => 30],
      ['surah_name' => 'Al-Ahzab', 'ayat' => 73],
      ['surah_name' => 'Saba', 'ayat' => 54],
      ['surah_name' => 'Fatir', 'ayat' => 45],
      ['surah_name' => 'Ya-Sin', 'ayat' => 83],
      ['surah_name' => 'As-Saffat', 'ayat' => 182],
      ['surah_name' => 'Sad', 'ayat' => 88],
      ['surah_name' => 'Az-Zumar', 'ayat' => 75],
      ['surah_name' => 'Ghafir', 'ayat' => 85],
      ['surah_name' => 'Fussilat', 'ayat' => 54],
      ['surah_name' => 'Ash-Shura', 'ayat' => 53],
      ['surah_name' => 'Az-Zukhruf', 'ayat' => 89],
      ['surah_name' => 'Ad-Dukhan', 'ayat' => 59],
      ['surah_name' => 'Al-Jathiya', 'ayat' => 37],
      ['surah_name' => 'Al-Ahqaf', 'ayat' => 35],
      ['surah_name' => 'Muhammad', 'ayat' => 38],
      ['surah_name' => 'Al-Fath', 'ayat' => 29],
      ['surah_name' => 'Al-Hujurat', 'ayat' => 18],
      ['surah_name' => 'Qaf', 'ayat' => 45],
      ['surah_name' => 'Adh-Dhariyat', 'ayat' => 60],
      ['surah_name' => 'At-Tur', 'ayat' => 49],
      ['surah_name' => 'An-Najm', 'ayat' => 62],
      ['surah_name' => 'Al-Qamar', 'ayat' => 55],
      ['surah_name' => 'Ar-Rahman', 'ayat' => 78],
      ['surah_name' => 'Al-Waqia', 'ayat' => 96],
      ['surah_name' => 'Al-Hadid', 'ayat' => 29],
      ['surah_name' => 'Al-Mujadila', 'ayat' => 22],
      ['surah_name' => 'Al-Hashr', 'ayat' => 24],
      ['surah_name' => 'Al-Mumtahana', 'ayat' => 13],
      ['surah_name' => 'As-Saff', 'ayat' => 14],
      ['surah_name' => 'Al-Jumua', 'ayat' => 11],
      ['surah_name' => 'Al-Munafiqun', 'ayat' => 11],
      ['surah_name' => 'At-Taghabun', 'ayat' => 18],
      ['surah_name' => 'At-Talaq', 'ayat' => 12],
      ['surah_name' => 'At-Tahrim', 'ayat' => 12],
      ['surah_name' => 'Al-Mulk', 'ayat' => 30],
      ['surah_name' => 'Al-Qalam', 'ayat' => 52],
      ['surah_name' => 'Al-Haqqa', 'ayat' => 52],
      ['surah_name' => 'Al-Maarij', 'ayat' => 44],
      ['surah_name' => 'Nuh', 'ayat' => 28],
      ['surah_name' => 'Al-Jinn', 'ayat' => 28],
      ['surah_name' => 'Al-Muzzammil', 'ayat' => 20],
      ['surah_name' => 'Al-Muddathir', 'ayat' => 56],
      ['surah_name' => 'Al-Qiyama', 'ayat' => 40],
      ['surah_name' => 'Al-Insan', 'ayat' => 31],
      ['surah_name' => 'Al-Mursalat', 'ayat' => 50],
      ['surah_name' => 'An-Naba', 'ayat' => 40],
      ['surah_name' => 'An-Naziat', 'ayat' => 46],
      ['surah_name' => 'Abasa', 'ayat' => 42],
      ['surah_name' => 'At-Takwir', 'ayat' => 29],
      ['surah_name' => 'Al-Infitar', 'ayat' => 19],
      ['surah_name' => 'Al-Mutaffifin', 'ayat' => 36],
      ['surah_name' => 'Al-Inshiqaq', 'ayat' => 25],
      ['surah_name' => 'Al-Buruj', 'ayat' => 22],
      ['surah_name' => 'At-Tariq', 'ayat' => 17],
      ['surah_name' => 'Al-Ala', 'ayat' => 19],
      ['surah_name' => 'Al-Ghashiya', 'ayat' => 26],
      ['surah_name' => 'Al-Fajr', 'ayat' => 30],
      ['surah_name' => 'Al-Balad', 'ayat' => 20],
      ['surah_name' => 'Ash-Shams', 'ayat' => 15],
      ['surah_name' => 'Al-Lail', 'ayat' => 21],
      ['surah_name' => 'Ad-Duhaa', 'ayat' => 11],
      ['surah_name' => 'Ash-Sharh', 'ayat' => 8],
      ['surah_name' => 'At-Tin', 'ayat' => 8],
      ['surah_name' => 'Al-Alaq', 'ayat' => 19],
      ['surah_name' => 'Al-Qadr', 'ayat' => 5],
      ['surah_name' => 'Al-Bayyina', 'ayat' => 8],
      ['surah_name' => 'Az-Zalzala', 'ayat' => 8],
      ['surah_name' => 'Al-Adiyat', 'ayat' => 11],
      ['surah_name' => 'Al-Qaria', 'ayat' => 11],
      ['surah_name' => 'At-Takathur', 'ayat' => 8],
      ['surah_name' => 'Al-Asr', 'ayat' => 3],
      ['surah_name' => 'Al-Humaza', 'ayat' => 9],
      ['surah_name' => 'Al-Fil', 'ayat' => 5],
      ['surah_name' => 'Quraysh', 'ayat' => 4],
      ['surah_name' => 'Al-Maun', 'ayat' => 7],
      ['surah_name' => 'Al-Kawthar', 'ayat' => 3],
      ['surah_name' => 'Al-Kafirun', 'ayat' => 6],
      ['surah_name' => 'An-Nasr', 'ayat' => 3],
      ['surah_name' => 'Al-Masad', 'ayat' => 5],
      ['surah_name' => 'Al-Ikhlas', 'ayat' => 4],
      ['surah_name' => 'Al-Falaq', 'ayat' => 5],
      ['surah_name' => 'An-Nas', 'ayat' => 6],
    ]);
  }
}
